
services:
  database:
    image: postgres:latest
    container_name: spring-data
    environment:
      - POSTGRES_DB=e-commerce
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_ROOT_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - my-database:/var/lib/postgres


volumes:
  my-database: