
services:
  database:
    image: postgres:latest
    container_name: spring-data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_ROOT_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - my-database:/var/lib/postgres


volumes:
  my-database: