spring:

  application:
    name: BackendShop
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  prefix: /api/v1
springdoc:
  override-with-generic-response: false

application:
  api:
    prefix: /api/v1
  security:
    jwt:
      secret-key: 13pFaaR/NALZzMGy1gmmAzVIDC42e+4e1Qd+9SHbQNs=
      expiration: 900000
      refresh-token:
        expiration: 3600000
  file-store: /Users/prpasn/Desktop/Coding/WebApp/e-commerce/uploads